# -*- coding: utf-8 -*-
"""Shipment Analytics Merge.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xSvXhPbCYZTBKv_jQFu_UHapan379MFj
"""

import pandas as pd
import numpy as np

customers = pd.read_csv('/content/customers.csv')
routes = pd.read_csv('routes.csv')
shipments = pd.read_csv('shipments.csv')
status_history = pd.read_csv('status_history.csv')

# Convert kolom tanggal
for col in ['pickup_date', 'estimated_delivery', 'actual_delivery']:
    shipments[col] = pd.to_datetime(shipments[col], errors='coerce')
status_history['update_timestamp'] = pd.to_datetime(status_history['update_timestamp'], errors='coerce')
customers['registration_date'] = pd.to_datetime(customers['registration_date'], errors='coerce')

# drop kolom yang tidak diperlukan

customers_slim = customers[['customer_id', 'customer_type', 'city', 'province', 'registration_date']].rename(
    columns={'city': 'customer_city', 'province': 'customer_province'}
)

routes_slim = routes[['route_id', 'origin_city', 'destination_city', 'distance_km',
                       'estimated_days_regular', 'estimated_days_express',
                       'price_per_kg_regular', 'price_per_kg_express']]

shipments_slim = shipments[['shipment_id', 'customer_id', 'route_id', 'weight_kg',
                             'package_type', 'service_type', 'pickup_date',
                             'estimated_delivery', 'actual_delivery', 'status',
                             'total_cost_idr']]

# agregrasi

status_history_sorted = status_history.sort_values(['shipment_id', 'update_timestamp'])

status_summary = status_history_sorted.groupby('shipment_id').agg(
    total_status_updates=('status', 'count'),
    first_update=('update_timestamp', 'min'),
    last_update=('update_timestamp', 'max'),
    ever_failed_delivery=('status', lambda x: (x == 'failed_delivery').any()),
    failed_delivery_count=('status', lambda x: (x == 'failed_delivery').sum()),
).reset_index()

status_summary['processing_hours'] = (
    (status_summary['last_update'] - status_summary['first_update']).dt.total_seconds() / 3600
).round(1)

status_summary = status_summary[['shipment_id', 'total_status_updates',
                                  'ever_failed_delivery', 'failed_delivery_count',
                                  'processing_hours']]

# join tabel

master = shipments_slim.merge(customers_slim, on='customer_id', how='left')
master = master.merge(routes_slim, on='route_id', how='left')
master = master.merge(status_summary, on='shipment_id', how='left')

master['delay_days'] = (master['actual_delivery'] - master['estimated_delivery']).dt.days

def get_on_time_status(row):
    if row['status'] != 'delivered':
        return np.nan
    if pd.isna(row['actual_delivery']):
        return 'Unknown'
    return 'On Time' if row['delay_days'] <= 0 else 'Late'

master['is_on_time'] = master.apply(get_on_time_status, axis=1)

master['is_problematic'] = (
    master['status'].isin(['lost', 'returned']) | master['ever_failed_delivery'].fillna(False)
)

master['is_data_incomplete'] = (
    (master['status'] == 'delivered') & (master['actual_delivery'].isna())
)

master['estimated_days'] = np.where(
    master['service_type'] == 'express',
    master['estimated_days_express'],
    master['estimated_days_regular']
)

master['price_per_kg_reference'] = np.where(
    master['service_type'] == 'express',
    master['price_per_kg_express'],
    master['price_per_kg_regular']
)

master['pickup_year'] = master['pickup_date'].dt.year
master['pickup_month'] = master['pickup_date'].dt.month
master['pickup_year_month'] = master['pickup_date'].dt.to_period('M').astype(str)

master['route_name'] = master['origin_city'] + ' - ' + master['destination_city']

cols_order = [
    'shipment_id', 'customer_id', 'customer_type', 'customer_city', 'customer_province',
    'route_id', 'route_name', 'origin_city', 'destination_city', 'distance_km',
    'package_type', 'service_type', 'weight_kg',
    'pickup_date', 'pickup_year', 'pickup_month', 'pickup_year_month',
    'estimated_delivery', 'actual_delivery', 'estimated_days', 'delay_days',
    'is_on_time', 'is_data_incomplete',
    'status', 'is_problematic', 'ever_failed_delivery', 'failed_delivery_count',
    'total_status_updates', 'processing_hours',
    'price_per_kg_reference', 'total_cost_idr'
]
master = master[cols_order]

output_path = 'shipments_master.csv'
master.to_csv(output_path, index=False)

print("Berhasil! File tersimpan di:", output_path)
print("Shape akhir:", master.shape)
print("\nPreview:")
print(master.head(3).to_string())
print("\nJumlah is_data_incomplete (delivered tapi tanggal kosong):", master['is_data_incomplete'].sum())
print("\nMissing values per kolom:")
print(master.isnull().sum())

